BEGIN;

ALTER TABLE pacientes ADD COLUMN IF NOT EXISTS activo BOOLEAN;
UPDATE pacientes SET activo = TRUE WHERE activo IS NULL;
ALTER TABLE pacientes ALTER COLUMN activo SET DEFAULT TRUE;
ALTER TABLE pacientes ALTER COLUMN activo SET NOT NULL;

ALTER TABLE medicos ADD COLUMN IF NOT EXISTS activo BOOLEAN;
UPDATE medicos SET activo = TRUE WHERE activo IS NULL;
ALTER TABLE medicos ALTER COLUMN activo SET DEFAULT TRUE;
ALTER TABLE medicos ALTER COLUMN activo SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_pacientes_dni ON pacientes (dni);

COMMIT;
